server {
    listen 80;
    client_max_body_size 100M;

    #backend
    location /api/ {
        proxy_pass http://fastapi:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /docs {
        proxy_pass http://fastapi:8000;
        proxy_set_header Host $host;
    }

    location /openapi.json {
        proxy_pass http://fastapi:8000;
        proxy_set_header Host $host;
    }


    #frontend
    location / {
        proxy_pass http://react:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }


    #volume de arquivos de midia
    location /midias/ {
        proxy_pass http://fastapi:8000;
        proxy_set_header Host $host;
    }
}