"""add usuario_nome to historico

Revision ID: 259e70a6e1c1
Revises: 78d99e256149
Create Date: 2026-04-29 09:30:11.948818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '259e70a6e1c1'
down_revision: Union[str, Sequence[str], None] = '78d99e256149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historico', sa.Column('usuario_nome', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historico', 'usuario_nome')
    # ### end Alembic commands ###
