"""troca de validade por inicio_exibicao e expiracao

Revision ID: 5f7843f46462
Revises: 7799f79aa713
Create Date: 2026-04-15 03:41:25.943950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f7843f46462'
down_revision: Union[str, Sequence[str], None] = '7799f79aa713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('midias', sa.Column('inicio_exibicao', sa.DateTime(timezone=True), nullable=True))
    op.add_column('midias', sa.Column('expiracao', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('midias', 'validade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('midias', sa.Column('validade', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('midias', 'expiracao')
    op.drop_column('midias', 'inicio_exibicao')
    # ### end Alembic commands ###
