"""add validade to midia

Revision ID: 7799f79aa713
Revises: deaa20fde222
Create Date: 2026-04-08 00:20:16.740589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7799f79aa713'
down_revision: Union[str, Sequence[str], None] = 'deaa20fde222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('midias', sa.Column('validade', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('midias', 'validade')
    # ### end Alembic commands ###
