"""add historico table

Revision ID: 78d99e256149
Revises: 5f7843f46462
Create Date: 2026-04-29 08:05:01.068319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78d99e256149'
down_revision: Union[str, Sequence[str], None] = '5f7843f46462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidade', sa.String(), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=False),
    sa.Column('entidade_nome', sa.String(), nullable=False),
    sa.Column('acao', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_id'), 'historico', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historico_id'), table_name='historico')
    op.drop_table('historico')
    # ### end Alembic commands ###
