"""nova coluna url na tabela midia

Revision ID: f53bfc856af8
Revises: dd44433e5ff8
Create Date: 2026-05-25 22:42:59.822273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f53bfc856af8'
down_revision: Union[str, Sequence[str], None] = 'dd44433e5ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('midias', sa.Column('url_externa', sa.String(), nullable=True))
    op.alter_column('midias', 'arquivo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('midias', 'arquivo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('midias', 'url_externa')
    # ### end Alembic commands ###
